"""The authoritative Scheme A domain manifest.

Operation tuples contain: base id, the ordered executable decomposition labels,
and the user-facing target effect used by canonical domain templates.
"""

DOMAIN_TITLES = {
    "inventory_fulfillment": "Enterprise Inventory and Fulfillment",
    "pricing_billing": "Enterprise Pricing and Billing",
    "procurement_suppliers": "Enterprise Procurement and Suppliers",
    "customer_support": "Enterprise Customer Support and Cases",
    "workforce_access": "Enterprise Workforce and Access Control",
    "finance_ledger": "Enterprise Finance and Ledger",
    "compliance_audit": "Enterprise Compliance and Audit",
    "contracts_documents": "Enterprise Contracts and Documents",
}

OPERATIONS = {
"inventory_fulfillment": [
("resolve_sellable_units", "read_on_hand+read_active_reservations+subtract", "quantity currently available to sell after active reservations"),
("resolve_transferable_units", "read_on_hand+read_active_reservations+apply_safety_stock", "quantity transferable after reservations and safety stock"),
("resolve_reorder_quantity", "read_projected_demand+read_reorder_policy+calculate_shortfall", "recommended replenishment quantity"),
("resolve_backorder_priority", "read_open_orders+read_priority_policy+rank_orders", "ordered backorder priority"),
("resolve_pick_location", "read_bin_inventory+filter_eligible_bins+rank_pick_bins", "eligible picking bin"),
("resolve_replenishment_source", "read_source_inventory+filter_transferable_sources+rank_sources", "replenishment source warehouse"),
("resolve_cycle_count_variance", "read_physical_count+read_book_quantity+compare_quantities", "physical-versus-book variance"),
("resolve_expiry_risk", "read_lot_dates+read_expiry_policy+classify_risk", "lot expiry risk class"),
("resolve_fulfillment_feasibility", "read_order_lines+read_sellable_stock+evaluate_all_lines", "whole-order fulfillment feasibility"),
("resolve_capacity_utilization", "read_location_capacity+aggregate_on_hand_volume+calculate_ratio", "warehouse capacity utilization ratio"),],
"pricing_billing": [
("resolve_list_price", "read_price_book+select_effective_record", "effective list price"),
("resolve_promotional_price", "read_list_price+read_active_promotion+apply_discount", "promotion-adjusted price"),
("resolve_contract_price", "read_contract_terms+read_list_price+apply_contract_rule", "customer-contract price"),
("resolve_tax_amount", "read_tax_rule+classify_item+apply_tax_rate", "applicable tax amount"),
("resolve_shipping_charge", "read_rate_card+classify_package+apply_zone_rate", "shipping charge"),
("resolve_service_fee", "read_fee_schedule+select_fee_tier", "service fee"),
("resolve_margin_floor", "read_cost_basis+read_margin_policy+calculate_floor", "minimum allowed sale price"),
("resolve_order_total", "read_line_prices+apply_order_discount+apply_tax_and_fee", "complete order total"),
("resolve_credit_adjustment", "read_invoice_state+read_adjustment_rule+calculate_credit", "invoice credit adjustment"),
("resolve_currency_amount", "read_exchange_rate+normalize_amount+convert_currency", "converted monetary amount"),],
"procurement_suppliers": [
("resolve_supplier_eligibility", "read_supplier_profile+read_eligibility_policy+evaluate_policy", "supplier eligibility decision"),
("resolve_quote_rank", "read_supplier_quotes+normalize_quote_terms+rank_quotes", "ordered supplier quote ranking"),
("resolve_purchase_limit", "read_budget_state+read_approval_policy+calculate_limit", "allowed purchase limit"),
("resolve_order_split", "read_supplier_capacity+read_requested_quantity+allocate_quantity", "purchase allocation across suppliers"),
("resolve_lead_time", "read_supplier_lane+read_business_calendar+calculate_arrival", "expected supplier arrival date"),
("resolve_contract_compliance", "read_contract_terms+read_purchase_order+compare_terms", "purchase-order contract compliance"),
("resolve_receipt_variance", "read_purchase_order+read_goods_receipt+compare_receipt", "goods receipt variance"),
("resolve_return_authorization", "read_receipt_state+read_return_policy+evaluate_return", "return authorization decision"),
("resolve_vendor_score", "read_performance_events+weight_metrics+aggregate_score", "supplier performance score"),
("resolve_expedite_decision", "read_demand_risk+read_supplier_options+choose_expedite", "expedite decision and option"),],
"customer_support": [
("resolve_case_owner", "read_case_attributes+read_routing_policy+select_owner", "assigned support case owner"),
("resolve_case_priority", "read_case_signals+read_severity_rule+classify_priority", "support case priority"),
("resolve_service_entitlement", "read_customer_plan+read_issue_class+evaluate_entitlement", "service entitlement decision"),
("resolve_refund_eligibility", "read_order_state+read_refund_policy+evaluate_refund", "refund eligibility decision"),
("resolve_sla_deadline", "read_case_timestamp+read_sla_rule+calculate_deadline", "service-level deadline"),
("resolve_next_action", "read_case_state+read_workflow_rule+select_transition", "next case workflow action"),
("resolve_duplicate_case", "read_case_features+search_similar_cases+score_similarity", "duplicate-case candidate"),
("resolve_escalation_target", "read_case_state+read_escalation_policy+select_target", "case escalation target"),
("resolve_contact_channel", "read_customer_preferences+read_channel_policy+select_channel", "customer contact channel"),
("resolve_case_closure", "read_resolution_evidence+read_closure_rule+validate_closure", "case closure permission"),],
"workforce_access": [
("resolve_access_decision", "read_identity_state+read_resource_policy+evaluate_access", "resource access allow-or-deny decision"),
("resolve_role_assignment", "read_job_profile+read_role_matrix+select_role", "assigned workforce role"),
("resolve_shift_eligibility", "read_employee_state+read_shift_rule+evaluate_shift", "shift eligibility decision"),
("resolve_leave_balance", "read_leave_ledger+filter_effective_entries+aggregate_balance", "remaining leave balance"),
("resolve_overtime_approval", "read_work_hours+read_overtime_policy+evaluate_overtime", "overtime approval decision"),
("resolve_training_requirement", "read_assigned_role+read_training_matrix+derive_requirements", "required employee training list"),
("resolve_delegation_scope", "read_delegation_record+read_scope_policy+calculate_scope", "effective delegation scope"),
("resolve_oncall_assignment", "read_roster+filter_available_staff+rank_candidates", "on-call staff assignee"),
("resolve_badge_expiry", "read_badge_record+read_validity_policy+calculate_expiry", "employee badge expiry date"),
("resolve_offboarding_actions", "read_employment_state+read_offboarding_matrix+derive_actions", "ordered employee offboarding actions"),],
"finance_ledger": [
("resolve_book_balance", "read_posted_entries+filter_as_of_date+aggregate_amount", "posted ledger book balance"),
("resolve_available_balance", "read_book_balance+read_holds+subtract_holds", "account balance available after holds"),
("resolve_transaction_fee", "read_transaction+read_fee_schedule+calculate_fee", "transaction fee"),
("resolve_reconciliation_status", "read_statement_total+read_ledger_total+compare_totals", "statement reconciliation status"),
("resolve_budget_variance", "read_budget+read_actuals+calculate_variance", "budget-versus-actual variance"),
("resolve_tax_basis", "read_transactions+apply_tax_classification+aggregate_basis", "taxable transaction basis"),
("resolve_fx_settlement", "read_source_amount+read_fx_rate+convert_and_round", "foreign-exchange settlement amount"),
("resolve_payment_status", "read_payment_events+apply_status_precedence+select_status", "effective payment status"),
("resolve_journal_total", "read_journal_lines+validate_balance+aggregate_lines", "balanced journal total"),
("resolve_audit_flag", "read_account_events+read_audit_rules+classify_flags", "account audit flags"),],
"compliance_audit": [
("resolve_control_status", "read_control_evidence+read_control_rule+evaluate_status", "control operating status"),
("resolve_evidence_completeness", "read_required_evidence+read_submitted_evidence+compare_sets", "control evidence completeness"),
("resolve_policy_applicability", "read_entity_attributes+read_policy_scope+evaluate_scope", "policy applicability decision"),
("resolve_exception_expiry", "read_exception_record+read_extension_history+calculate_expiry", "policy exception expiry date"),
("resolve_risk_rating", "read_risk_factors+read_scoring_matrix+calculate_rating", "compliance risk rating"),
("resolve_audit_sample", "read_population+read_sampling_rule+select_sample", "deterministic audit sample"),
("resolve_segregation_conflict", "read_role_assignments+read_conflict_matrix+detect_conflicts", "segregation-of-duties conflicts"),
("resolve_retention_deadline", "read_record_class+read_retention_rule+calculate_deadline", "record retention deadline"),
("resolve_remediation_owner", "read_finding_attributes+read_ownership_matrix+select_owner", "finding remediation owner"),
("resolve_filing_readiness", "read_filing_requirements+read_current_artifacts+validate_readiness", "regulatory filing readiness"),],
"contracts_documents": [
("resolve_effective_clause", "read_contract_versions+select_effective_version+extract_clause", "effective contract clause"),
("resolve_obligation_owner", "read_clause_obligations+read_party_mapping+select_owner", "contract obligation owner"),
("resolve_contract_deadline", "read_clause_dates+read_calendar_rule+calculate_deadline", "contractual deadline"),
("resolve_latest_version", "read_revision_history+filter_approved_revisions+select_latest", "latest approved document revision"),
("resolve_document_access", "read_document_acl+read_requester_role+evaluate_access", "document access decision"),
("resolve_citation_target", "read_citation_index+filter_citation_type+select_target", "document citation target"),
("resolve_amendment_impact", "read_base_contract+read_amendment+compute_changed_obligations", "contract amendment obligation impact"),
("resolve_signature_status", "read_signature_events+apply_signature_rule+select_status", "contract signature status"),
("resolve_retention_class", "read_document_metadata+read_classification_rule+classify_record", "document retention class"),
("resolve_section_summary", "read_document_section+extract_key_facts+compose_summary", "structured section key-fact summary"),],
}

# Literal business-language anchors used only to validate LLM-written query text.
# They are intentionally independent of tool names and executable semantics.
QUERY_SEMANTIC_ANCHORS = {
    "resolve_sellable_units": ("available to sell", "reservations"),
    "resolve_transferable_units": ("transferable", "safety stock"),
    "resolve_reorder_quantity": ("replenishment quantity",),
    "resolve_backorder_priority": ("backorder priority",),
    "resolve_pick_location": ("picking bin",),
    "resolve_replenishment_source": ("source warehouse",),
    "resolve_cycle_count_variance": ("physical", "book variance"),
    "resolve_expiry_risk": ("expiry risk",),
    "resolve_fulfillment_feasibility": ("fulfillment feasibility",),
    "resolve_capacity_utilization": ("capacity utilization",),
    "resolve_list_price": ("list price",),
    "resolve_promotional_price": ("promotion-adjusted price",),
    "resolve_contract_price": ("contract price",),
    "resolve_tax_amount": ("tax amount",),
    "resolve_shipping_charge": ("shipping charge",),
    "resolve_service_fee": ("service fee",),
    "resolve_margin_floor": ("minimum allowed sale price",),
    "resolve_order_total": ("order total",),
    "resolve_credit_adjustment": ("credit adjustment",),
    "resolve_currency_amount": ("converted", "amount"),
    "resolve_supplier_eligibility": ("supplier eligibility",),
    "resolve_quote_rank": ("supplier quote ranking",),
    "resolve_purchase_limit": ("purchase limit",),
    "resolve_order_split": ("purchase allocation", "suppliers"),
    "resolve_lead_time": ("supplier arrival date",),
    "resolve_contract_compliance": ("contract compliance",),
    "resolve_receipt_variance": ("goods receipt variance",),
    "resolve_return_authorization": ("return authorization",),
    "resolve_vendor_score": ("supplier performance score",),
    "resolve_expedite_decision": ("expedite decision", "option"),
    "resolve_case_owner": ("support case owner",),
    "resolve_case_priority": ("case priority",),
    "resolve_service_entitlement": ("service entitlement",),
    "resolve_refund_eligibility": ("refund eligibility",),
    "resolve_sla_deadline": ("service-level deadline",),
    "resolve_next_action": ("workflow action",),
    "resolve_duplicate_case": ("duplicate-case candidate",),
    "resolve_escalation_target": ("escalation target",),
    "resolve_contact_channel": ("contact channel",),
    "resolve_case_closure": ("case closure permission",),
    "resolve_access_decision": ("access", "allow-or-deny"),
    "resolve_role_assignment": ("workforce role",),
    "resolve_shift_eligibility": ("shift eligibility",),
    "resolve_leave_balance": ("leave balance",),
    "resolve_overtime_approval": ("overtime approval",),
    "resolve_training_requirement": ("training", "required"),
    "resolve_delegation_scope": ("delegation scope",),
    "resolve_oncall_assignment": ("on-call", "assignee"),
    "resolve_badge_expiry": ("badge expiry date",),
    "resolve_offboarding_actions": ("offboarding actions",),
    "resolve_book_balance": ("ledger book balance",),
    "resolve_available_balance": ("available", "after holds"),
    "resolve_transaction_fee": ("transaction fee",),
    "resolve_reconciliation_status": ("reconciliation status",),
    "resolve_budget_variance": ("budget", "actual variance"),
    "resolve_tax_basis": ("taxable transaction basis",),
    "resolve_fx_settlement": ("foreign-exchange settlement amount",),
    "resolve_payment_status": ("payment status",),
    "resolve_journal_total": ("balanced journal total",),
    "resolve_audit_flag": ("account audit flags",),
    "resolve_control_status": ("control operating status",),
    "resolve_evidence_completeness": ("evidence completeness",),
    "resolve_policy_applicability": ("policy applicability",),
    "resolve_exception_expiry": ("exception expiry date",),
    "resolve_risk_rating": ("compliance risk rating",),
    "resolve_audit_sample": ("audit sample",),
    "resolve_segregation_conflict": ("segregation-of-duties conflicts",),
    "resolve_retention_deadline": ("retention deadline",),
    "resolve_remediation_owner": ("remediation owner",),
    "resolve_filing_readiness": ("filing readiness",),
    "resolve_effective_clause": ("contract clause",),
    "resolve_obligation_owner": ("obligation owner",),
    "resolve_contract_deadline": ("contractual deadline",),
    "resolve_latest_version": ("latest approved", "revision"),
    "resolve_document_access": ("document access",),
    "resolve_citation_target": ("citation target",),
    "resolve_amendment_impact": ("amendment", "obligation impact"),
    "resolve_signature_status": ("signature status",),
    "resolve_retention_class": ("retention class",),
    "resolve_section_summary": ("section", "key-fact summary"),
}

RESOURCE_DECLARATIONS = {
"inventory_fulfillment": "inventory_snapshot(sku:string,warehouse_id:string,on_hand_units:integer,book_units:integer,volume_per_unit:number);active_reservations(reservation_id:string,sku:string,warehouse_id:string,reserved_units:integer,status:string);safety_stock_policy(sku:string,warehouse_id:string,minimum_units:integer);demand_forecast(sku:string,warehouse_id:string,projected_units:integer,horizon_days:integer);reorder_policy(sku:string,warehouse_id:string,target_cover_units:integer,minimum_order_units:integer);open_orders(order_id:string,customer_tier:string,requested_at:string,priority_signal:string,status:string);priority_rules(rule_id:string,customer_tier:string,priority_signal:string,priority_weight:integer);order_lines(order_id:string,sku:string,requested_units:integer);bin_inventory(bin_id:string,sku:string,warehouse_id:string,available_units:integer,pick_sequence:integer,blocked:boolean);source_inventory(source_warehouse_id:string,destination_warehouse_id:string,sku:string,on_hand_units:integer,reserved_units:integer,safety_stock_units:integer,transfer_cost:number);physical_counts(count_id:string,sku:string,warehouse_id:string,physical_units:integer,counted_at:string);lots(lot_id:string,sku:string,warehouse_id:string,quantity:integer,expiry_date:string);expiry_policy(policy_id:string,warning_days:integer,critical_days:integer);location_capacity(warehouse_id:string,capacity_volume:number)",
"pricing_billing": "price_book(item_id:string,region:string,effective_from:string,effective_to:string,list_price:number);item_catalog(item_id:string,item_class:string,package_id:string);packages(package_id:string,zone:string,package_class:string,weight_kg:number);promotions(promotion_id:string,item_id:string,region:string,discount_type:string,discount_value:number,active_from:string,active_to:string);customer_contracts(contract_id:string,customer_id:string,item_id:string,pricing_rule:string,adjustment_value:number);tax_rules(tax_region:string,item_class:string,rate:number,effective_from:string,effective_to:string);shipping_rate_cards(rate_card_id:string,zone:string,package_class:string,minimum_charge:number,per_kg_rate:number);fee_schedules(fee_schedule_id:string,tier_min:number,tier_max:number,fee_type:string,fee_value:number);fee_context(transaction_id:string,amount:number,fee_schedule_id:string);cost_basis(item_id:string,region:string,unit_cost:number);margin_policy(policy_id:string,item_class:string,minimum_margin_rate:number);order_headers(order_id:string,customer_id:string,region:string,promotion_id:string,fee_schedule_id:string);order_lines(order_id:string,item_id:string,quantity:integer);discount_rules(rule_id:string,discount_type:string,discount_value:number);invoice_state(invoice_id:string,order_id:string,paid_amount:number,credited_amount:number,status:string);adjustment_rules(rule_id:string,status:string,adjustment_type:string,adjustment_value:number);exchange_rates(rate_date:string,source_currency:string,target_currency:string,rate:number);currency_requests(request_id:string,amount:number,source_currency:string,target_currency:string,rate_date:string)",
"procurement_suppliers": "supplier_profiles(supplier_id:string,region:string,category:string,status:string,certification_level:integer);eligibility_policies(policy_id:string,category:string,allowed_statuses:array,minimum_certification:integer);supplier_quotes(quote_id:string,supplier_id:string,item_id:string,unit_price:number,currency:string,lead_days:integer,validity_date:string);budget_state(cost_center_id:string,period:string,available_amount:number);approval_policies(policy_id:string,amount_threshold:number,approver_level:string);supplier_capacity(supplier_id:string,item_id:string,available_units:integer);requested_purchases(request_id:string,item_id:string,requested_quantity:integer,required_date:string);supplier_lanes(supplier_id:string,destination_id:string,transit_business_days:integer);business_calendars(calendar_id:string,date:string,is_business_day:boolean);contracts(contract_id:string,supplier_id:string,item_id:string,max_quantity:integer,allowed_price:number,terms_code:string);purchase_orders(po_id:string,contract_id:string,supplier_id:string,item_id:string,ordered_quantity:integer,unit_price:number);goods_receipts(receipt_id:string,po_id:string,received_quantity:integer,received_item_id:string,received_at:string,status:string);return_policies(policy_id:string,receipt_status:string,max_age_days:integer,allowed:boolean);supplier_performance(supplier_id:string,metric:string,value:number,event_date:string);demand_risk(request_id:string,shortage_score:number,deadline_risk:number);supplier_options(request_id:string,supplier_id:string,expedite_cost:number,expedited_days:integer)",
"customer_support": "cases(case_id:string,customer_id:string,issue_class:string,product_id:string,created_at:string,current_status:string,severity_signal:string);routing_policies(policy_id:string,issue_class:string,region:string,owner_team:string);severity_rules(rule_id:string,issue_class:string,signal:string,priority:string);customer_plans(customer_id:string,plan_id:string,service_level:string);service_entitlement_rules(plan_id:string,issue_class:string,entitled:boolean);order_state(order_id:string,customer_id:string,status:string,delivered_at:string,amount:number);refund_policies(policy_id:string,order_status:string,max_age_days:integer,maximum_amount:number,eligible:boolean);sla_rules(rule_id:string,priority:string,duration_minutes:integer,business_calendar:string);business_calendars(calendar_id:string,date:string,is_business_day:boolean);workflow_rules(rule_id:string,current_status:string,issue_class:string,next_action:string);case_features(case_id:string,feature_name:string,feature_value:string);case_similarity_index(case_id:string,candidate_case_id:string,similarity_score:number);escalation_policies(rule_id:string,priority:string,current_status:string,target_team:string);customer_preferences(customer_id:string,preferred_channel:string,blocked_channels:array);channel_policies(issue_class:string,priority:string,allowed_channels:array);resolution_evidence(case_id:string,evidence_type:string,accepted:boolean);closure_rules(rule_id:string,issue_class:string,required_evidence:array,terminal_statuses:array);staff_roster(owner_id:string,team:string,skill:string,capacity:integer,active:boolean)",
"workforce_access": "identity_state(person_id:string,employment_status:string,department:string,location:string,clearance_level:integer);resource_policies(policy_id:string,resource_id:string,minimum_clearance:integer,allowed_roles:array,allowed_statuses:array);role_assignments(person_id:string,role_id:string,resource_id:string);job_profiles(job_id:string,department:string,level:integer,duties_code:string);role_matrix(duties_code:string,role_id:string,priority:integer);employee_state(employee_id:string,status:string,job_id:string,location:string);shift_rules(rule_id:string,shift_id:string,required_role:string,minimum_rest_hours:number);work_history(employee_id:string,shift_id:string,start_time:string,end_time:string);leave_ledger(employee_id:string,entry_date:string,entry_type:string,units:number);overtime_policy(policy_id:string,role_id:string,weekly_limit:number,approval_threshold:number);training_matrix(role_id:string,training_code:string,required:boolean);training_records(employee_id:string,training_code:string,status:string,expiry_date:string);delegation_records(delegation_id:string,delegator_id:string,delegate_id:string,scope_code:string,start_date:string,end_date:string);scope_policy(scope_code:string,allowed_actions:array);roster(employee_id:string,role_id:string,available_date:string,capacity:integer,active:boolean);badge_records(employee_id:string,badge_id:string,issued_at:string,badge_class:string);validity_policy(badge_class:string,validity_days:integer);offboarding_matrix(job_id:string,action_code:string,sequence:integer)",
"finance_ledger": "accounts(account_id:string,account_type:string,currency:string,status:string);ledger_entries(entry_id:string,account_id:string,posted_at:string,amount:number,debit_credit:string,transaction_type:string,posted:boolean);holds(hold_id:string,account_id:string,amount:number,status:string,effective_at:string,expires_at:string);fee_schedules(fee_schedule_id:string,transaction_type:string,minimum_fee:number,rate:number,maximum_fee:number);transactions(transaction_id:string,account_id:string,amount:number,transaction_type:string,occurred_at:string,source_currency:string,target_currency:string);statements(statement_id:string,account_id:string,period:string,closing_total:number);budgets(budget_id:string,cost_center_id:string,period:string,planned_amount:number);actuals(cost_center_id:string,period:string,actual_amount:number);tax_rules(rule_id:string,transaction_type:string,tax_class:string);exchange_rates(rate_date:string,source_currency:string,target_currency:string,rate:number,rounding_digits:integer);payment_events(payment_id:string,event_time:string,event_type:string,status_code:string);journals(journal_id:string,line_id:string,account_id:string,debit:number,credit:number);audit_rules(rule_id:string,event_type:string,threshold:number,flag_code:string);account_events(account_id:string,event_id:string,event_type:string,value:number,occurred_at:string)",
"compliance_audit": "controls(control_id:string,control_family:string,owner_id:string,status_rule_id:string);control_evidence(control_id:string,evidence_id:string,evidence_type:string,status:string,submitted_at:string);control_rules(rule_id:string,required_evidence_types:array,pass_conditions:array);policies(policy_id:string,scope_expression:string,effective_from:string,effective_to:string);entities(entity_id:string,entity_type:string,region:string,attributes:object);exceptions(exception_id:string,policy_id:string,entity_id:string,approved_at:string,original_expiry:string);exception_extensions(exception_id:string,extension_date:string,days:integer);risk_factors(subject_id:string,factor_code:string,factor_value:number);risk_scoring_matrix(matrix_id:string,factor_code:string,range_min:number,range_max:number,score:number);audit_population(population_id:string,record_id:string,stratum:string,risk_score:number);sampling_rules(rule_id:string,sample_size:integer,stratified:boolean,seed_salt:string);role_assignments(person_id:string,role_id:string,entity_id:string);conflict_matrix(role_a:string,role_b:string,conflict_code:string);record_classes(record_class:string,retention_rule_id:string);retention_rules(rule_id:string,years:integer,trigger_event:string);record_events(record_id:string,event_type:string,event_date:string);findings(finding_id:string,entity_id:string,finding_type:string,severity:string,department:string);ownership_matrix(finding_type:string,department:string,owner_id:string);filing_requirements(filing_id:string,artifact_type:string,required:boolean);current_artifacts(entity_id:string,artifact_type:string,status:string)",
"contracts_documents": "contracts(contract_id:string,party_a:string,party_b:string,effective_date:string,status:string);contract_versions(contract_id:string,version_id:string,approved:boolean,effective_from:string,effective_to:string);clauses(contract_id:string,version_id:string,clause_id:string,clause_type:string,text:string,section_id:string);clause_obligations(clause_id:string,obligation_id:string,party_role:string,due_rule_id:string);party_mapping(contract_id:string,party_role:string,party_id:string);clause_dates(clause_id:string,date_type:string,date_value:string);calendar_rules(rule_id:string,offset_days:integer,business_calendar:string);business_calendars(calendar_id:string,date:string,is_business_day:boolean);revision_history(document_id:string,revision_id:string,approved:boolean,approved_at:string,supersedes:string);document_acl(document_id:string,role_id:string,permission:string);requester_roles(requester_id:string,role_id:string);citation_index(document_id:string,citation_type:string,citation_id:string,target_id:string);amendments(contract_id:string,amendment_id:string,effective_date:string,changed_clause_id:string,replacement_text:string);signature_events(contract_id:string,party_id:string,event_type:string,event_time:string);signature_rules(rule_id:string,required_parties:array,accepted_event_types:array);document_metadata(document_id:string,document_type:string,owner_id:string,sensitivity:string);classification_rules(rule_id:string,document_type:string,sensitivity:string,retention_class:string);document_sections(document_id:string,section_id:string,text:string)",
}
